# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loteriamodel',
            old_name='vyzrebovanieCisla',
            new_name='vyzrebovaneCisla',
        ),
        migrations.AlterField(
            model_name='loteriamodel',
            name='casZrebovania',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
