
POCET_CISEL_NA_TIKETE = 5
MIN_CISLO_NA_TIKETE = 1
MAX_CISLO_NA_TIKETE = 40
POCET_CISEL_V_LOTERII = MAX_CISLO_NA_TIKETE-MIN_CISLO_NA_TIKETE+1
WAIT_TIME_FOR_NUMBER = 1
JACKPOT = 1000000
WAIT_TIME_FOR_LOTTERY = 1